import os
from PIL import Image, ImageDraw

def draw_grid(name, grid_str, colors):
    img = Image.new("RGBA", (50, 50), (255, 255, 255, 0))
    draw = ImageDraw.Draw(img)
    lines = [line.strip() for line in grid_str.strip().split('\n') if line.strip()]
    for y, row in enumerate(lines):
        if y >= 10: break
        for x, char in enumerate(row):
            if x >= 10: break
            if char in colors:
                color = colors[char]
                draw.rectangle([x*5, y*5, x*5+4, y*5+4], fill=color)
    img.save(f"images/animals/{name}_50x50.png")
    print(f"Fixed {name}_50x50.png")

animals = {
    "fox": {
        "grid": """
..........
.O......O.
.OO....OO.
.OOOOOOOO.
.OOOOOOOO.
.OWOOOOWO.
.OWBOOBWO.
.OWWOOWW..
..WWWWWW..
..........
""",
        "colors": {'O': (217, 100, 31), 'W': (255, 255, 255), 'B': (0, 0, 0)}
    },
    "cat": {
        "grid": """
..........
.G......G.
.DG....GD.
.DGGGGGGD.
.GGGGGGGG.
.GGBGGBGG.
.GPGGGGP..
.GGGGGGGG.
..GGGGGG..
..........
""",
        "colors": {'G': (150, 150, 150), 'D': (100, 100, 100), 'P': (255, 180, 200), 'B': (0, 0, 0)}
    },
    "shark": {
        "grid": """
..........
..........
....D.....
...BBB....
..BBBBB...
.BBBKBWW..
BBBBBBWWW.
.BBBBBB...
...D......
..........
""",
        "colors": {'B': (100, 130, 160), 'D': (70, 100, 130), 'W': (255, 255, 255), 'K': (0, 0, 0)}
    },
    "lizard": {
        "grid": """
..........
...LL.....
..LGBG....
.LGGLGL...
LGDG.GDG..
...G......
...G......
...GG.....
....DG....
..........
""",
        "colors": {'G': (50, 180, 50), 'L': (100, 220, 100), 'D': (20, 120, 20), 'B': (0, 0, 0)}
    },
    "whale": {
        "grid": """
..........
....L.....
...LLL....
..........
..BBBBBB..
.BBKBBBBBB
.BBBBBBBBB
.WWWWWWW..
..B...B...
..........
""",
        "colors": {'B': (50, 100, 180), 'L': (150, 200, 255), 'W': (255, 255, 255), 'K': (0, 0, 0)}
    },
    "dolphin": {
        "grid": """
..........
..........
....D.....
...GGGG...
..GGGKG...
.GGGGGGG..
.GGGGGG...
GG..W.....
..........
..........
""",
        "colors": {'G': (120, 160, 200), 'W': (255, 255, 255), 'K': (0, 0, 0), 'D': (80, 120, 160)}
    },
    "crab": {
        "grid": """
..........
.R......R.
.RD....DR.
..RRRRRR..
.RRKRRKRR.
.RRRRRRRR.
D.RRRRRR.D
.D.R..R.D.
..........
..........
""",
        "colors": {'R': (220, 50, 50), 'D': (150, 20, 20), 'K': (0, 0, 0)}
    },
    "squirrel": {
        "grid": """
..........
....B..D..
...BL.DDD.
...BKB.DD.
...BLB.BD.
...BBB.BD.
.BBBBBBBD.
BBLLBBB...
BBBBBB....
..........
""",
        "colors": {'B': (180, 100, 50), 'L': (220, 150, 100), 'D': (120, 60, 20), 'K': (0, 0, 0)}
    },
    "zebra": {
        "grid": """
..........
...WW.....
..KWWK....
..WKWK....
.WWKWW....
.WKWKW....
.GWWWG....
.W..W.....
.W..W.....
..........
""",
        "colors": {'W': (255, 255, 255), 'K': (0, 0, 0), 'G': (200, 200, 200)}
    },
    "giraffe": {
        "grid": """
..........
..Y..Y....
..Y..Y....
..YYYY....
..YKYK....
..YYYY....
...BB.....
...YY.....
...YB.....
...YY.....
""",
        "colors": {'Y': (255, 200, 50), 'B': (150, 80, 20), 'K': (0, 0, 0)}
    },
    "hippo": {
        "grid": """
..........
..........
..GGGGGG..
.GGKGGKGG.
.GPGGGGPG.
.DGGGGGGD.
.DGGGGGGD.
..DG..GD..
..........
..........
""",
        "colors": {'G': (150, 150, 160), 'D': (100, 100, 110), 'P': (200, 150, 150), 'K': (0, 0, 0)}
    },
    "rhino": {
        "grid": """
..........
..........
...L......
..LGG.....
.LGKGGG...
.GGGGGGGG.
.DGGGGGGD.
..DG..GD..
..........
..........
""",
        "colors": {'G': (160, 160, 160), 'L': (200, 200, 200), 'D': (120, 120, 120), 'K': (0, 0, 0)}
    },
    "cheetah": {
        "grid": """
..........
...YY.....
..YKYK....
..YWYW....
.YKYYYY...
.YYYKYK...
.YYYYYY...
.Y...Y....
.Y...Y....
..........
""",
        "colors": {'Y': (240, 180, 50), 'K': (0, 0, 0), 'W': (255, 255, 255)}
    },
    "parrot": {
        "grid": """
..........
..........
...RRR....
..RWRR....
..RKRW....
...RRY....
...RBB....
...RB.....
..........
..........
""",
        "colors": {'R': (220, 30, 30), 'B': (30, 80, 220), 'Y': (240, 220, 30), 'K': (0, 0, 0), 'W': (255, 255, 255)}
    }
}

for name, data in animals.items():
    draw_grid(name, data['grid'], data['colors'])
